---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: aiworkshop

resources:
- ./llama-cpu/
- namespace.yaml
- user1-to-admin.yaml
- 3scale-network-policy.yaml
