kind: Template
apiVersion: template.openshift.io/v1
metadata:
  annotations:
    argocd.argoproj.io/managed-by: openshift-gitops
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    openshift.io/display-name: Custom - vLLM ServingRuntime - CPU
    template.openshift.io/long-description: This template defines resources needed to deploy vLLM ServingRuntime with KServe in Red Hat OpenShift AI
    internal.config.kubernetes.io/previousNamespaces: opendatahub
    internal.config.kubernetes.io/previousKinds: Template
    opendatahub.io/modelServingSupport: '["single"]'
    internal.config.kubernetes.io/previousNames: vllm-runtime-template-cpu
    opendatahub.io/apiProtocol: REST
    tags: 'rhods,rhoai,kserve,servingruntime'
    description: vLLM is a high-throughput and memory-efficient inference and serving engine for LLMs
    template.openshift.io/documentation-url: 'https://github.com/opendatahub-io/vllm'
    openshift.io/provider-display-name: 'Red Hat, Inc.'
  name: vllm-runtime-template-cpu
  namespace: redhat-ods-applications
  labels:
    app: odh-dashboard
    app.kubernetes.io/part-of: model-mesh
    app.opendatahub.io/model-mesh: 'true'
    opendatahub.io/dashboard: 'true'
    opendatahub.io/ootb: 'false'
objects:
  - apiVersion: serving.kserve.io/v1alpha1
    kind: ServingRuntime
    metadata:
      annotations:
        opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
        openshift.io/display-name: Custom - vLLM ServingRuntime - CPU
      labels:
        opendatahub.io/dashboard: 'true'
      name: vllm-runtime-cpu
    spec:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '8080'
      containers:
        - args:
            - --model
            - /mnt/models/
            - --port
            - "8080"
            - --max-model-len
            - "2048"
          image: quay.io/rh-aiservices-bu/vllm-cpu-openai-ubi9:0.3
          name: kserve-container
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
      multiModel: false
      supportedModelFormats:
        - autoSelect: true
          name: vLLM
