---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/openshift-gitops-operator.openshift-gitops-operator: ''
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  channel: latest
  config:
    env:
      - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
        value: 'openshift-gitops,openshift-policy'
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators-snapshot-gitops
  sourceNamespace: openshift-gitops-operator