---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  annotations:
    controller.devfile.io/allow-import-from: '*'
  name: web-terminal-tooling
  namespace: openshift-operators
  labels:
    console.openshift.io/terminal: 'true'
spec:
  attributes:
    controller.devfile.io/storage-type: per-workspace
  components:
    - container:
        args:
          - tail
          - '-f'
          - /dev/null
        cpuLimit: 400m
        cpuRequest: 100m
        image: {{ .Values.image }}
        memoryLimit: 512Mi
        memoryRequest: 128Mi
        mountSources: false
        sourceMapping: /projects
        volumeMounts:
          - name: home-storage
            path: /home/user
      name: web-terminal-tooling
    - name: home-storage
      volume:
        ephemeral: false
