---
helmCharts:
  - name: vault-0.30.0
    namespace: vault
    includeCRDs: false
    valuesFile: values/vault-values.yaml
    version: 0.30.0
    releaseName: vault
    repo:  # we expand chart in folder as we have no helm chart repo
