---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: delivery

resources:
- namespace.yaml
# - image-puller.yaml

# components:
# - ./nvidia-console-plugin
helmGlobals:
  chartHome: ../.helm/charts
helmCharts:
  - name: image-puller
    releaseName: image-puller
    version: 0.1.0
    valuesFile: image-puller-values.yaml
