---
apiVersion: v1
kind: Namespace
metadata:
  name: vllm
  labels:
    argocd.argoproj.io/managed-by: openshift-policy
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    argocd.argoproj.io/managed-by: openshift-policy
  name: image-puller
